create table Intranet_Satff (
	uuid_ VARCHAR(75) null,
	id_ LONG not null primary key,
	user_id LONG,
	city VARCHAR(75) null,
	name VARCHAR(75) null,
	turnover_time DATE null,
	entry_time DATE null,
	base_pay DOUBLE,
	performance_pay DOUBLE,
	wage_subtotal DOUBLE,
	insurance_base DOUBLE,
	endowment_insurance DOUBLE,
	unemployment_insurance DOUBLE,
	work_injury_insurance DOUBLE,
	birth_insurance DOUBLE,
	medical_insurance DOUBLE,
	individual_insurance DOUBLE,
	housing_accumulation_fund_base DOUBLE,
	individual_pay DOUBLE,
	amount_payable DOUBLE,
	people_together DOUBLE,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table Intranet_satff (
	uuid_ VARCHAR(75) null,
	id_ LONG not null primary key,
	user_id LONG,
	city VARCHAR(75) null,
	name VARCHAR(75) null,
	base_pay DOUBLE,
	performance_pay DOUBLE,
	wage_subtotal DOUBLE,
	insurance_base DOUBLE,
	endowment_insurance DOUBLE,
	unemployment_insurance DOUBLE,
	work_injury_insurance DOUBLE,
	birth_insurance DOUBLE,
	medical_insurance DOUBLE,
	individual_insurance DOUBLE,
	housing_accumulation_fund_base DOUBLE,
	individual_pay DOUBLE,
	amount_payable DOUBLE,
	people_together DOUBLE,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);