/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the basic_information service. Represents a row in the &quot;Intranet_basic_information&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.basic_informationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.basic_informationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see basic_information
 * @see com.shuntian.portlet.intranet.model.impl.basic_informationImpl
 * @see com.shuntian.portlet.intranet.model.impl.basic_informationModelImpl
 * @generated
 */
public interface basic_informationModel extends BaseModel<basic_information>,
	StagedModel, TrashedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a basic_information model instance should use the {@link basic_information} interface instead.
	 */

	/**
	 * Returns the primary key of this basic_information.
	 *
	 * @return the primary key of this basic_information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this basic_information.
	 *
	 * @param primaryKey the primary key of this basic_information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this basic_information.
	 *
	 * @return the uuid of this basic_information
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this basic_information.
	 *
	 * @param uuid the uuid of this basic_information
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the staff ID of this basic_information.
	 *
	 * @return the staff ID of this basic_information
	 */
	public long getStaffId();

	/**
	 * Sets the staff ID of this basic_information.
	 *
	 * @param staffId the staff ID of this basic_information
	 */
	public void setStaffId(long staffId);

	/**
	 * Returns the user ID of this basic_information.
	 *
	 * @return the user ID of this basic_information
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this basic_information.
	 *
	 * @param userId the user ID of this basic_information
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this basic_information.
	 *
	 * @return the user uuid of this basic_information
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this basic_information.
	 *
	 * @param userUuid the user uuid of this basic_information
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this basic_information.
	 *
	 * @return the name of this basic_information
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this basic_information.
	 *
	 * @param name the name of this basic_information
	 */
	public void setName(String name);

	/**
	 * Returns the sex of this basic_information.
	 *
	 * @return the sex of this basic_information
	 */
	@AutoEscape
	public String getSex();

	/**
	 * Sets the sex of this basic_information.
	 *
	 * @param sex the sex of this basic_information
	 */
	public void setSex(String sex);

	/**
	 * Returns the id_number of this basic_information.
	 *
	 * @return the id_number of this basic_information
	 */
	@AutoEscape
	public String getId_number();

	/**
	 * Sets the id_number of this basic_information.
	 *
	 * @param id_number the id_number of this basic_information
	 */
	public void setId_number(String id_number);

	/**
	 * Returns the nation of this basic_information.
	 *
	 * @return the nation of this basic_information
	 */
	@AutoEscape
	public String getNation();

	/**
	 * Sets the nation of this basic_information.
	 *
	 * @param nation the nation of this basic_information
	 */
	public void setNation(String nation);

	/**
	 * Returns the place_of_origin of this basic_information.
	 *
	 * @return the place_of_origin of this basic_information
	 */
	@AutoEscape
	public String getPlace_of_origin();

	/**
	 * Sets the place_of_origin of this basic_information.
	 *
	 * @param place_of_origin the place_of_origin of this basic_information
	 */
	public void setPlace_of_origin(String place_of_origin);

	/**
	 * Returns the account_properties of this basic_information.
	 *
	 * @return the account_properties of this basic_information
	 */
	@AutoEscape
	public String getAccount_properties();

	/**
	 * Sets the account_properties of this basic_information.
	 *
	 * @param account_properties the account_properties of this basic_information
	 */
	public void setAccount_properties(String account_properties);

	/**
	 * Returns the birth of this basic_information.
	 *
	 * @return the birth of this basic_information
	 */
	public Date getBirth();

	/**
	 * Sets the birth of this basic_information.
	 *
	 * @param birth the birth of this basic_information
	 */
	public void setBirth(Date birth);

	/**
	 * Returns the marital_status of this basic_information.
	 *
	 * @return the marital_status of this basic_information
	 */
	@AutoEscape
	public String getMarital_status();

	/**
	 * Sets the marital_status of this basic_information.
	 *
	 * @param marital_status the marital_status of this basic_information
	 */
	public void setMarital_status(String marital_status);

	/**
	 * Returns the highest_degree of this basic_information.
	 *
	 * @return the highest_degree of this basic_information
	 */
	@AutoEscape
	public String getHighest_degree();

	/**
	 * Sets the highest_degree of this basic_information.
	 *
	 * @param highest_degree the highest_degree of this basic_information
	 */
	public void setHighest_degree(String highest_degree);

	/**
	 * Returns the political_background of this basic_information.
	 *
	 * @return the political_background of this basic_information
	 */
	@AutoEscape
	public String getPolitical_background();

	/**
	 * Sets the political_background of this basic_information.
	 *
	 * @param political_background the political_background of this basic_information
	 */
	public void setPolitical_background(String political_background);

	/**
	 * Returns the file_location of this basic_information.
	 *
	 * @return the file_location of this basic_information
	 */
	@AutoEscape
	public String getFile_location();

	/**
	 * Sets the file_location of this basic_information.
	 *
	 * @param file_location the file_location of this basic_information
	 */
	public void setFile_location(String file_location);

	/**
	 * Returns the base_pay of this basic_information.
	 *
	 * @return the base_pay of this basic_information
	 */
	public double getBase_pay();

	/**
	 * Sets the base_pay of this basic_information.
	 *
	 * @param base_pay the base_pay of this basic_information
	 */
	public void setBase_pay(double base_pay);

	/**
	 * Returns the performance_pay of this basic_information.
	 *
	 * @return the performance_pay of this basic_information
	 */
	public double getPerformance_pay();

	/**
	 * Sets the performance_pay of this basic_information.
	 *
	 * @param performance_pay the performance_pay of this basic_information
	 */
	public void setPerformance_pay(double performance_pay);

	/**
	 * Returns the health of this basic_information.
	 *
	 * @return the health of this basic_information
	 */
	@AutoEscape
	public String getHealth();

	/**
	 * Sets the health of this basic_information.
	 *
	 * @param health the health of this basic_information
	 */
	public void setHealth(String health);

	/**
	 * Returns the contact_phone of this basic_information.
	 *
	 * @return the contact_phone of this basic_information
	 */
	@AutoEscape
	public String getContact_phone();

	/**
	 * Sets the contact_phone of this basic_information.
	 *
	 * @param contact_phone the contact_phone of this basic_information
	 */
	public void setContact_phone(String contact_phone);

	/**
	 * Returns the mail of this basic_information.
	 *
	 * @return the mail of this basic_information
	 */
	@AutoEscape
	public String getMail();

	/**
	 * Sets the mail of this basic_information.
	 *
	 * @param mail the mail of this basic_information
	 */
	public void setMail(String mail);

	/**
	 * Returns the domicile of this basic_information.
	 *
	 * @return the domicile of this basic_information
	 */
	@AutoEscape
	public String getDomicile();

	/**
	 * Sets the domicile of this basic_information.
	 *
	 * @param domicile the domicile of this basic_information
	 */
	public void setDomicile(String domicile);

	/**
	 * Returns the residence_phone of this basic_information.
	 *
	 * @return the residence_phone of this basic_information
	 */
	@AutoEscape
	public String getResidence_phone();

	/**
	 * Sets the residence_phone of this basic_information.
	 *
	 * @param residence_phone the residence_phone of this basic_information
	 */
	public void setResidence_phone(String residence_phone);

	/**
	 * Returns the current_residential_address of this basic_information.
	 *
	 * @return the current_residential_address of this basic_information
	 */
	@AutoEscape
	public String getCurrent_residential_address();

	/**
	 * Sets the current_residential_address of this basic_information.
	 *
	 * @param current_residential_address the current_residential_address of this basic_information
	 */
	public void setCurrent_residential_address(
		String current_residential_address);

	/**
	 * Returns the current_residential_address_phone of this basic_information.
	 *
	 * @return the current_residential_address_phone of this basic_information
	 */
	@AutoEscape
	public String getCurrent_residential_address_phone();

	/**
	 * Sets the current_residential_address_phone of this basic_information.
	 *
	 * @param current_residential_address_phone the current_residential_address_phone of this basic_information
	 */
	public void setCurrent_residential_address_phone(
		String current_residential_address_phone);

	/**
	 * Returns the emergency_contact of this basic_information.
	 *
	 * @return the emergency_contact of this basic_information
	 */
	@AutoEscape
	public String getEmergency_contact();

	/**
	 * Sets the emergency_contact of this basic_information.
	 *
	 * @param emergency_contact the emergency_contact of this basic_information
	 */
	public void setEmergency_contact(String emergency_contact);

	/**
	 * Returns the emergency_contact_relation of this basic_information.
	 *
	 * @return the emergency_contact_relation of this basic_information
	 */
	@AutoEscape
	public String getEmergency_contact_relation();

	/**
	 * Sets the emergency_contact_relation of this basic_information.
	 *
	 * @param emergency_contact_relation the emergency_contact_relation of this basic_information
	 */
	public void setEmergency_contact_relation(String emergency_contact_relation);

	/**
	 * Returns the emergency_contact_phone of this basic_information.
	 *
	 * @return the emergency_contact_phone of this basic_information
	 */
	@AutoEscape
	public String getEmergency_contact_phone();

	/**
	 * Sets the emergency_contact_phone of this basic_information.
	 *
	 * @param emergency_contact_phone the emergency_contact_phone of this basic_information
	 */
	public void setEmergency_contact_phone(String emergency_contact_phone);

	/**
	 * Returns the company ID of this basic_information.
	 *
	 * @return the company ID of this basic_information
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this basic_information.
	 *
	 * @param companyId the company ID of this basic_information
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the createuser of this basic_information.
	 *
	 * @return the createuser of this basic_information
	 */
	public long getCreateuser();

	/**
	 * Sets the createuser of this basic_information.
	 *
	 * @param createuser the createuser of this basic_information
	 */
	public void setCreateuser(long createuser);

	/**
	 * Returns the create date of this basic_information.
	 *
	 * @return the create date of this basic_information
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this basic_information.
	 *
	 * @param createDate the create date of this basic_information
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modifieduser of this basic_information.
	 *
	 * @return the modifieduser of this basic_information
	 */
	public long getModifieduser();

	/**
	 * Sets the modifieduser of this basic_information.
	 *
	 * @param modifieduser the modifieduser of this basic_information
	 */
	public void setModifieduser(long modifieduser);

	/**
	 * Returns the modified date of this basic_information.
	 *
	 * @return the modified date of this basic_information
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this basic_information.
	 *
	 * @param modifiedDate the modified date of this basic_information
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this basic_information.
	 *
	 * @return the status of this basic_information
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this basic_information was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this basic_information.
	 *
	 * @return the trash entry created when this basic_information was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this basic_information.
	 *
	 * @return the class primary key of the trash entry for this basic_information
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this basic_information.
	 *
	 * @return the trash handler for this basic_information
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this basic_information is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this basic_information is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this basic_information is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this basic_information is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(basic_information basic_information);

	@Override
	public int hashCode();

	@Override
	public CacheModel<basic_information> toCacheModel();

	@Override
	public basic_information toEscapedModel();

	@Override
	public basic_information toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}