/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the education service. Represents a row in the &quot;Intranet_education&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.educationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.educationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see education
 * @see com.shuntian.portlet.intranet.model.impl.educationImpl
 * @see com.shuntian.portlet.intranet.model.impl.educationModelImpl
 * @generated
 */
public interface educationModel extends BaseModel<education>, StagedModel,
	TrashedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a education model instance should use the {@link education} interface instead.
	 */

	/**
	 * Returns the primary key of this education.
	 *
	 * @return the primary key of this education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this education.
	 *
	 * @param primaryKey the primary key of this education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this education.
	 *
	 * @return the uuid of this education
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this education.
	 *
	 * @param uuid the uuid of this education
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the education ID of this education.
	 *
	 * @return the education ID of this education
	 */
	public long getEducationId();

	/**
	 * Sets the education ID of this education.
	 *
	 * @param educationId the education ID of this education
	 */
	public void setEducationId(long educationId);

	/**
	 * Returns the satff ID of this education.
	 *
	 * @return the satff ID of this education
	 */
	public long getSatffId();

	/**
	 * Sets the satff ID of this education.
	 *
	 * @param satffId the satff ID of this education
	 */
	public void setSatffId(long satffId);

	/**
	 * Returns the witness of this education.
	 *
	 * @return the witness of this education
	 */
	@AutoEscape
	public String getWitness();

	/**
	 * Sets the witness of this education.
	 *
	 * @param witness the witness of this education
	 */
	public void setWitness(String witness);

	/**
	 * Returns the professional of this education.
	 *
	 * @return the professional of this education
	 */
	@AutoEscape
	public String getProfessional();

	/**
	 * Sets the professional of this education.
	 *
	 * @param professional the professional of this education
	 */
	public void setProfessional(String professional);

	/**
	 * Returns the university of this education.
	 *
	 * @return the university of this education
	 */
	@AutoEscape
	public String getUniversity();

	/**
	 * Sets the university of this education.
	 *
	 * @param university the university of this education
	 */
	public void setUniversity(String university);

	/**
	 * Returns the contact_phone of this education.
	 *
	 * @return the contact_phone of this education
	 */
	@AutoEscape
	public String getContact_phone();

	/**
	 * Sets the contact_phone of this education.
	 *
	 * @param contact_phone the contact_phone of this education
	 */
	public void setContact_phone(String contact_phone);

	/**
	 * Returns the start_stop_time of this education.
	 *
	 * @return the start_stop_time of this education
	 */
	public Date getStart_stop_time();

	/**
	 * Sets the start_stop_time of this education.
	 *
	 * @param start_stop_time the start_stop_time of this education
	 */
	public void setStart_stop_time(Date start_stop_time);

	/**
	 * Returns the company ID of this education.
	 *
	 * @return the company ID of this education
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this education.
	 *
	 * @param companyId the company ID of this education
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the createuser of this education.
	 *
	 * @return the createuser of this education
	 */
	public long getCreateuser();

	/**
	 * Sets the createuser of this education.
	 *
	 * @param createuser the createuser of this education
	 */
	public void setCreateuser(long createuser);

	/**
	 * Returns the create date of this education.
	 *
	 * @return the create date of this education
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this education.
	 *
	 * @param createDate the create date of this education
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modifieduser of this education.
	 *
	 * @return the modifieduser of this education
	 */
	public long getModifieduser();

	/**
	 * Sets the modifieduser of this education.
	 *
	 * @param modifieduser the modifieduser of this education
	 */
	public void setModifieduser(long modifieduser);

	/**
	 * Returns the modified date of this education.
	 *
	 * @return the modified date of this education
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this education.
	 *
	 * @param modifiedDate the modified date of this education
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this education.
	 *
	 * @return the status of this education
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this education was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this education.
	 *
	 * @return the trash entry created when this education was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this education.
	 *
	 * @return the class primary key of the trash entry for this education
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this education.
	 *
	 * @return the trash handler for this education
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this education is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this education is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this education is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this education is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(education education);

	@Override
	public int hashCode();

	@Override
	public CacheModel<education> toCacheModel();

	@Override
	public education toEscapedModel();

	@Override
	public education toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}