/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the family service. Represents a row in the &quot;Intranet_family&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.familyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.familyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see family
 * @see com.shuntian.portlet.intranet.model.impl.familyImpl
 * @see com.shuntian.portlet.intranet.model.impl.familyModelImpl
 * @generated
 */
public interface familyModel extends BaseModel<family>, StagedModel, TrashedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a family model instance should use the {@link family} interface instead.
	 */

	/**
	 * Returns the primary key of this family.
	 *
	 * @return the primary key of this family
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this family.
	 *
	 * @param primaryKey the primary key of this family
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this family.
	 *
	 * @return the uuid of this family
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this family.
	 *
	 * @param uuid the uuid of this family
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the family ID of this family.
	 *
	 * @return the family ID of this family
	 */
	public long getFamilyId();

	/**
	 * Sets the family ID of this family.
	 *
	 * @param familyId the family ID of this family
	 */
	public void setFamilyId(long familyId);

	/**
	 * Returns the satff ID of this family.
	 *
	 * @return the satff ID of this family
	 */
	public long getSatffId();

	/**
	 * Sets the satff ID of this family.
	 *
	 * @param satffId the satff ID of this family
	 */
	public void setSatffId(long satffId);

	/**
	 * Returns the name of this family.
	 *
	 * @return the name of this family
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this family.
	 *
	 * @param name the name of this family
	 */
	public void setName(String name);

	/**
	 * Returns the relationship of this family.
	 *
	 * @return the relationship of this family
	 */
	@AutoEscape
	public String getRelationship();

	/**
	 * Sets the relationship of this family.
	 *
	 * @param relationship the relationship of this family
	 */
	public void setRelationship(String relationship);

	/**
	 * Returns the work_unit of this family.
	 *
	 * @return the work_unit of this family
	 */
	@AutoEscape
	public String getWork_unit();

	/**
	 * Sets the work_unit of this family.
	 *
	 * @param work_unit the work_unit of this family
	 */
	public void setWork_unit(String work_unit);

	/**
	 * Returns the contact_phone of this family.
	 *
	 * @return the contact_phone of this family
	 */
	@AutoEscape
	public String getContact_phone();

	/**
	 * Sets the contact_phone of this family.
	 *
	 * @param contact_phone the contact_phone of this family
	 */
	public void setContact_phone(String contact_phone);

	/**
	 * Returns the once_job of this family.
	 *
	 * @return the once_job of this family
	 */
	@AutoEscape
	public String getOnce_job();

	/**
	 * Sets the once_job of this family.
	 *
	 * @param once_job the once_job of this family
	 */
	public void setOnce_job(String once_job);

	/**
	 * Returns the company ID of this family.
	 *
	 * @return the company ID of this family
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this family.
	 *
	 * @param companyId the company ID of this family
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the createuser of this family.
	 *
	 * @return the createuser of this family
	 */
	public long getCreateuser();

	/**
	 * Sets the createuser of this family.
	 *
	 * @param createuser the createuser of this family
	 */
	public void setCreateuser(long createuser);

	/**
	 * Returns the create date of this family.
	 *
	 * @return the create date of this family
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this family.
	 *
	 * @param createDate the create date of this family
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modifieduser of this family.
	 *
	 * @return the modifieduser of this family
	 */
	public long getModifieduser();

	/**
	 * Sets the modifieduser of this family.
	 *
	 * @param modifieduser the modifieduser of this family
	 */
	public void setModifieduser(long modifieduser);

	/**
	 * Returns the modified date of this family.
	 *
	 * @return the modified date of this family
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this family.
	 *
	 * @param modifiedDate the modified date of this family
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this family.
	 *
	 * @return the status of this family
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this family was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this family.
	 *
	 * @return the trash entry created when this family was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this family.
	 *
	 * @return the class primary key of the trash entry for this family
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this family.
	 *
	 * @return the trash handler for this family
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this family is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this family is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this family is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this family is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(family family);

	@Override
	public int hashCode();

	@Override
	public CacheModel<family> toCacheModel();

	@Override
	public family toEscapedModel();

	@Override
	public family toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}