/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the work service. Represents a row in the &quot;Intranet_work&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.workModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.workImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see work
 * @see com.shuntian.portlet.intranet.model.impl.workImpl
 * @see com.shuntian.portlet.intranet.model.impl.workModelImpl
 * @generated
 */
public interface workModel extends BaseModel<work>, StagedModel, TrashedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work model instance should use the {@link work} interface instead.
	 */

	/**
	 * Returns the primary key of this work.
	 *
	 * @return the primary key of this work
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work.
	 *
	 * @param primaryKey the primary key of this work
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this work.
	 *
	 * @return the uuid of this work
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this work.
	 *
	 * @param uuid the uuid of this work
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the work ID of this work.
	 *
	 * @return the work ID of this work
	 */
	public long getWorkId();

	/**
	 * Sets the work ID of this work.
	 *
	 * @param workId the work ID of this work
	 */
	public void setWorkId(long workId);

	/**
	 * Returns the satff ID of this work.
	 *
	 * @return the satff ID of this work
	 */
	public long getSatffId();

	/**
	 * Sets the satff ID of this work.
	 *
	 * @param satffId the satff ID of this work
	 */
	public void setSatffId(long satffId);

	/**
	 * Returns the witness of this work.
	 *
	 * @return the witness of this work
	 */
	@AutoEscape
	public String getWitness();

	/**
	 * Sets the witness of this work.
	 *
	 * @param witness the witness of this work
	 */
	public void setWitness(String witness);

	/**
	 * Returns the once_job of this work.
	 *
	 * @return the once_job of this work
	 */
	@AutoEscape
	public String getOnce_job();

	/**
	 * Sets the once_job of this work.
	 *
	 * @param once_job the once_job of this work
	 */
	public void setOnce_job(String once_job);

	/**
	 * Returns the work_unit of this work.
	 *
	 * @return the work_unit of this work
	 */
	@AutoEscape
	public String getWork_unit();

	/**
	 * Sets the work_unit of this work.
	 *
	 * @param work_unit the work_unit of this work
	 */
	public void setWork_unit(String work_unit);

	/**
	 * Returns the contact_phone of this work.
	 *
	 * @return the contact_phone of this work
	 */
	@AutoEscape
	public String getContact_phone();

	/**
	 * Sets the contact_phone of this work.
	 *
	 * @param contact_phone the contact_phone of this work
	 */
	public void setContact_phone(String contact_phone);

	/**
	 * Returns the start_stop_time of this work.
	 *
	 * @return the start_stop_time of this work
	 */
	public Date getStart_stop_time();

	/**
	 * Sets the start_stop_time of this work.
	 *
	 * @param start_stop_time the start_stop_time of this work
	 */
	public void setStart_stop_time(Date start_stop_time);

	/**
	 * Returns the company ID of this work.
	 *
	 * @return the company ID of this work
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this work.
	 *
	 * @param companyId the company ID of this work
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the createuser of this work.
	 *
	 * @return the createuser of this work
	 */
	public long getCreateuser();

	/**
	 * Sets the createuser of this work.
	 *
	 * @param createuser the createuser of this work
	 */
	public void setCreateuser(long createuser);

	/**
	 * Returns the create date of this work.
	 *
	 * @return the create date of this work
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this work.
	 *
	 * @param createDate the create date of this work
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modifieduser of this work.
	 *
	 * @return the modifieduser of this work
	 */
	public long getModifieduser();

	/**
	 * Sets the modifieduser of this work.
	 *
	 * @param modifieduser the modifieduser of this work
	 */
	public void setModifieduser(long modifieduser);

	/**
	 * Returns the modified date of this work.
	 *
	 * @return the modified date of this work
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work.
	 *
	 * @param modifiedDate the modified date of this work
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this work.
	 *
	 * @return the status of this work
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this work was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this work.
	 *
	 * @return the trash entry created when this work was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this work.
	 *
	 * @return the class primary key of the trash entry for this work
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this work.
	 *
	 * @return the trash handler for this work
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this work is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this work is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this work is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this work is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(work work);

	@Override
	public int hashCode();

	@Override
	public CacheModel<work> toCacheModel();

	@Override
	public work toEscapedModel();

	@Override
	public work toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}