/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.ContainerModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;
import com.liferay.portlet.trash.model.TrashEntry;
import com.liferay.portlet.trash.service.TrashEntryLocalServiceUtil;

import com.shuntian.portlet.intranet.model.basic_information;
import com.shuntian.portlet.intranet.model.basic_informationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the basic_information service. Represents a row in the &quot;Intranet_basic_information&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.shuntian.portlet.intranet.model.basic_informationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link basic_informationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see basic_informationImpl
 * @see com.shuntian.portlet.intranet.model.basic_information
 * @see com.shuntian.portlet.intranet.model.basic_informationModel
 * @generated
 */
public class basic_informationModelImpl extends BaseModelImpl<basic_information>
	implements basic_informationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a basic_information model instance should use the {@link com.shuntian.portlet.intranet.model.basic_information} interface instead.
	 */
	public static final String TABLE_NAME = "Intranet_basic_information";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "staffId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "sex", Types.VARCHAR },
			{ "id_number", Types.VARCHAR },
			{ "nation", Types.VARCHAR },
			{ "place_of_origin", Types.VARCHAR },
			{ "account_properties", Types.VARCHAR },
			{ "birth", Types.TIMESTAMP },
			{ "marital_status", Types.VARCHAR },
			{ "highest_degree", Types.VARCHAR },
			{ "political_background", Types.VARCHAR },
			{ "file_location", Types.VARCHAR },
			{ "base_pay", Types.DOUBLE },
			{ "performance_pay", Types.DOUBLE },
			{ "health", Types.VARCHAR },
			{ "contact_phone", Types.VARCHAR },
			{ "mail", Types.VARCHAR },
			{ "domicile", Types.VARCHAR },
			{ "residence_phone", Types.VARCHAR },
			{ "current_residential_address", Types.VARCHAR },
			{ "current_residential_address_phone", Types.VARCHAR },
			{ "emergency_contact", Types.VARCHAR },
			{ "emergency_contact_relation", Types.VARCHAR },
			{ "emergency_contact_phone", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "createuser", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifieduser", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Intranet_basic_information (uuid_ VARCHAR(75) null,staffId LONG not null primary key,userId LONG,name VARCHAR(75) null,sex VARCHAR(75) null,id_number VARCHAR(75) null,nation VARCHAR(75) null,place_of_origin VARCHAR(75) null,account_properties VARCHAR(75) null,birth DATE null,marital_status VARCHAR(75) null,highest_degree VARCHAR(75) null,political_background VARCHAR(75) null,file_location VARCHAR(75) null,base_pay DOUBLE,performance_pay DOUBLE,health VARCHAR(75) null,contact_phone VARCHAR(75) null,mail VARCHAR(75) null,domicile VARCHAR(75) null,residence_phone VARCHAR(75) null,current_residential_address VARCHAR(75) null,current_residential_address_phone VARCHAR(75) null,emergency_contact VARCHAR(75) null,emergency_contact_relation VARCHAR(75) null,emergency_contact_phone VARCHAR(75) null,companyId LONG,createuser LONG,createDate DATE null,modifieduser LONG,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Intranet_basic_information";
	public static final String ORDER_BY_JPQL = " ORDER BY basic_information.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Intranet_basic_information.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.shuntian.portlet.intranet.model.basic_information"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.shuntian.portlet.intranet.model.basic_information"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.shuntian.portlet.intranet.model.basic_information"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long UUID_COLUMN_BITMASK = 2L;
	public static long CREATEDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.shuntian.portlet.intranet.model.basic_information"));

	public basic_informationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _staffId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStaffId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _staffId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return basic_information.class;
	}

	@Override
	public String getModelClassName() {
		return basic_information.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("staffId", getStaffId());
		attributes.put("userId", getUserId());
		attributes.put("name", getName());
		attributes.put("sex", getSex());
		attributes.put("id_number", getId_number());
		attributes.put("nation", getNation());
		attributes.put("place_of_origin", getPlace_of_origin());
		attributes.put("account_properties", getAccount_properties());
		attributes.put("birth", getBirth());
		attributes.put("marital_status", getMarital_status());
		attributes.put("highest_degree", getHighest_degree());
		attributes.put("political_background", getPolitical_background());
		attributes.put("file_location", getFile_location());
		attributes.put("base_pay", getBase_pay());
		attributes.put("performance_pay", getPerformance_pay());
		attributes.put("health", getHealth());
		attributes.put("contact_phone", getContact_phone());
		attributes.put("mail", getMail());
		attributes.put("domicile", getDomicile());
		attributes.put("residence_phone", getResidence_phone());
		attributes.put("current_residential_address",
			getCurrent_residential_address());
		attributes.put("current_residential_address_phone",
			getCurrent_residential_address_phone());
		attributes.put("emergency_contact", getEmergency_contact());
		attributes.put("emergency_contact_relation",
			getEmergency_contact_relation());
		attributes.put("emergency_contact_phone", getEmergency_contact_phone());
		attributes.put("companyId", getCompanyId());
		attributes.put("createuser", getCreateuser());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifieduser", getModifieduser());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long staffId = (Long)attributes.get("staffId");

		if (staffId != null) {
			setStaffId(staffId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String sex = (String)attributes.get("sex");

		if (sex != null) {
			setSex(sex);
		}

		String id_number = (String)attributes.get("id_number");

		if (id_number != null) {
			setId_number(id_number);
		}

		String nation = (String)attributes.get("nation");

		if (nation != null) {
			setNation(nation);
		}

		String place_of_origin = (String)attributes.get("place_of_origin");

		if (place_of_origin != null) {
			setPlace_of_origin(place_of_origin);
		}

		String account_properties = (String)attributes.get("account_properties");

		if (account_properties != null) {
			setAccount_properties(account_properties);
		}

		Date birth = (Date)attributes.get("birth");

		if (birth != null) {
			setBirth(birth);
		}

		String marital_status = (String)attributes.get("marital_status");

		if (marital_status != null) {
			setMarital_status(marital_status);
		}

		String highest_degree = (String)attributes.get("highest_degree");

		if (highest_degree != null) {
			setHighest_degree(highest_degree);
		}

		String political_background = (String)attributes.get(
				"political_background");

		if (political_background != null) {
			setPolitical_background(political_background);
		}

		String file_location = (String)attributes.get("file_location");

		if (file_location != null) {
			setFile_location(file_location);
		}

		Double base_pay = (Double)attributes.get("base_pay");

		if (base_pay != null) {
			setBase_pay(base_pay);
		}

		Double performance_pay = (Double)attributes.get("performance_pay");

		if (performance_pay != null) {
			setPerformance_pay(performance_pay);
		}

		String health = (String)attributes.get("health");

		if (health != null) {
			setHealth(health);
		}

		String contact_phone = (String)attributes.get("contact_phone");

		if (contact_phone != null) {
			setContact_phone(contact_phone);
		}

		String mail = (String)attributes.get("mail");

		if (mail != null) {
			setMail(mail);
		}

		String domicile = (String)attributes.get("domicile");

		if (domicile != null) {
			setDomicile(domicile);
		}

		String residence_phone = (String)attributes.get("residence_phone");

		if (residence_phone != null) {
			setResidence_phone(residence_phone);
		}

		String current_residential_address = (String)attributes.get(
				"current_residential_address");

		if (current_residential_address != null) {
			setCurrent_residential_address(current_residential_address);
		}

		String current_residential_address_phone = (String)attributes.get(
				"current_residential_address_phone");

		if (current_residential_address_phone != null) {
			setCurrent_residential_address_phone(current_residential_address_phone);
		}

		String emergency_contact = (String)attributes.get("emergency_contact");

		if (emergency_contact != null) {
			setEmergency_contact(emergency_contact);
		}

		String emergency_contact_relation = (String)attributes.get(
				"emergency_contact_relation");

		if (emergency_contact_relation != null) {
			setEmergency_contact_relation(emergency_contact_relation);
		}

		String emergency_contact_phone = (String)attributes.get(
				"emergency_contact_phone");

		if (emergency_contact_phone != null) {
			setEmergency_contact_phone(emergency_contact_phone);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long createuser = (Long)attributes.get("createuser");

		if (createuser != null) {
			setCreateuser(createuser);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long modifieduser = (Long)attributes.get("modifieduser");

		if (modifieduser != null) {
			setModifieduser(modifieduser);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getStaffId() {
		return _staffId;
	}

	@Override
	public void setStaffId(long staffId) {
		_staffId = staffId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getSex() {
		if (_sex == null) {
			return StringPool.BLANK;
		}
		else {
			return _sex;
		}
	}

	@Override
	public void setSex(String sex) {
		_sex = sex;
	}

	@Override
	public String getId_number() {
		if (_id_number == null) {
			return StringPool.BLANK;
		}
		else {
			return _id_number;
		}
	}

	@Override
	public void setId_number(String id_number) {
		_id_number = id_number;
	}

	@Override
	public String getNation() {
		if (_nation == null) {
			return StringPool.BLANK;
		}
		else {
			return _nation;
		}
	}

	@Override
	public void setNation(String nation) {
		_nation = nation;
	}

	@Override
	public String getPlace_of_origin() {
		if (_place_of_origin == null) {
			return StringPool.BLANK;
		}
		else {
			return _place_of_origin;
		}
	}

	@Override
	public void setPlace_of_origin(String place_of_origin) {
		_place_of_origin = place_of_origin;
	}

	@Override
	public String getAccount_properties() {
		if (_account_properties == null) {
			return StringPool.BLANK;
		}
		else {
			return _account_properties;
		}
	}

	@Override
	public void setAccount_properties(String account_properties) {
		_account_properties = account_properties;
	}

	@Override
	public Date getBirth() {
		return _birth;
	}

	@Override
	public void setBirth(Date birth) {
		_birth = birth;
	}

	@Override
	public String getMarital_status() {
		if (_marital_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _marital_status;
		}
	}

	@Override
	public void setMarital_status(String marital_status) {
		_marital_status = marital_status;
	}

	@Override
	public String getHighest_degree() {
		if (_highest_degree == null) {
			return StringPool.BLANK;
		}
		else {
			return _highest_degree;
		}
	}

	@Override
	public void setHighest_degree(String highest_degree) {
		_highest_degree = highest_degree;
	}

	@Override
	public String getPolitical_background() {
		if (_political_background == null) {
			return StringPool.BLANK;
		}
		else {
			return _political_background;
		}
	}

	@Override
	public void setPolitical_background(String political_background) {
		_political_background = political_background;
	}

	@Override
	public String getFile_location() {
		if (_file_location == null) {
			return StringPool.BLANK;
		}
		else {
			return _file_location;
		}
	}

	@Override
	public void setFile_location(String file_location) {
		_file_location = file_location;
	}

	@Override
	public double getBase_pay() {
		return _base_pay;
	}

	@Override
	public void setBase_pay(double base_pay) {
		_base_pay = base_pay;
	}

	@Override
	public double getPerformance_pay() {
		return _performance_pay;
	}

	@Override
	public void setPerformance_pay(double performance_pay) {
		_performance_pay = performance_pay;
	}

	@Override
	public String getHealth() {
		if (_health == null) {
			return StringPool.BLANK;
		}
		else {
			return _health;
		}
	}

	@Override
	public void setHealth(String health) {
		_health = health;
	}

	@Override
	public String getContact_phone() {
		if (_contact_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _contact_phone;
		}
	}

	@Override
	public void setContact_phone(String contact_phone) {
		_contact_phone = contact_phone;
	}

	@Override
	public String getMail() {
		if (_mail == null) {
			return StringPool.BLANK;
		}
		else {
			return _mail;
		}
	}

	@Override
	public void setMail(String mail) {
		_mail = mail;
	}

	@Override
	public String getDomicile() {
		if (_domicile == null) {
			return StringPool.BLANK;
		}
		else {
			return _domicile;
		}
	}

	@Override
	public void setDomicile(String domicile) {
		_domicile = domicile;
	}

	@Override
	public String getResidence_phone() {
		if (_residence_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _residence_phone;
		}
	}

	@Override
	public void setResidence_phone(String residence_phone) {
		_residence_phone = residence_phone;
	}

	@Override
	public String getCurrent_residential_address() {
		if (_current_residential_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _current_residential_address;
		}
	}

	@Override
	public void setCurrent_residential_address(
		String current_residential_address) {
		_current_residential_address = current_residential_address;
	}

	@Override
	public String getCurrent_residential_address_phone() {
		if (_current_residential_address_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _current_residential_address_phone;
		}
	}

	@Override
	public void setCurrent_residential_address_phone(
		String current_residential_address_phone) {
		_current_residential_address_phone = current_residential_address_phone;
	}

	@Override
	public String getEmergency_contact() {
		if (_emergency_contact == null) {
			return StringPool.BLANK;
		}
		else {
			return _emergency_contact;
		}
	}

	@Override
	public void setEmergency_contact(String emergency_contact) {
		_emergency_contact = emergency_contact;
	}

	@Override
	public String getEmergency_contact_relation() {
		if (_emergency_contact_relation == null) {
			return StringPool.BLANK;
		}
		else {
			return _emergency_contact_relation;
		}
	}

	@Override
	public void setEmergency_contact_relation(String emergency_contact_relation) {
		_emergency_contact_relation = emergency_contact_relation;
	}

	@Override
	public String getEmergency_contact_phone() {
		if (_emergency_contact_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _emergency_contact_phone;
		}
	}

	@Override
	public void setEmergency_contact_phone(String emergency_contact_phone) {
		_emergency_contact_phone = emergency_contact_phone;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getCreateuser() {
		return _createuser;
	}

	@Override
	public void setCreateuser(long createuser) {
		_createuser = createuser;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getModifieduser() {
		return _modifieduser;
	}

	@Override
	public void setModifieduser(long modifieduser) {
		_modifieduser = modifieduser;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				basic_information.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException {
		if (!isInTrash()) {
			return null;
		}

		TrashEntry trashEntry = TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		TrashHandler trashHandler = getTrashHandler();

		if (!Validator.isNull(trashHandler.getContainerModelClassName())) {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler = TrashHandlerRegistryUtil.getTrashHandler(trashHandler.getContainerModelClassName());

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public TrashHandler getTrashHandler() {
		return TrashHandlerRegistryUtil.getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		TrashHandler trashHandler = getTrashHandler();

		if ((trashHandler == null) ||
				Validator.isNull(trashHandler.getContainerModelClassName())) {
			return false;
		}

		try {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception e) {
		}

		return false;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			basic_information.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public basic_information toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (basic_information)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		basic_informationImpl basic_informationImpl = new basic_informationImpl();

		basic_informationImpl.setUuid(getUuid());
		basic_informationImpl.setStaffId(getStaffId());
		basic_informationImpl.setUserId(getUserId());
		basic_informationImpl.setName(getName());
		basic_informationImpl.setSex(getSex());
		basic_informationImpl.setId_number(getId_number());
		basic_informationImpl.setNation(getNation());
		basic_informationImpl.setPlace_of_origin(getPlace_of_origin());
		basic_informationImpl.setAccount_properties(getAccount_properties());
		basic_informationImpl.setBirth(getBirth());
		basic_informationImpl.setMarital_status(getMarital_status());
		basic_informationImpl.setHighest_degree(getHighest_degree());
		basic_informationImpl.setPolitical_background(getPolitical_background());
		basic_informationImpl.setFile_location(getFile_location());
		basic_informationImpl.setBase_pay(getBase_pay());
		basic_informationImpl.setPerformance_pay(getPerformance_pay());
		basic_informationImpl.setHealth(getHealth());
		basic_informationImpl.setContact_phone(getContact_phone());
		basic_informationImpl.setMail(getMail());
		basic_informationImpl.setDomicile(getDomicile());
		basic_informationImpl.setResidence_phone(getResidence_phone());
		basic_informationImpl.setCurrent_residential_address(getCurrent_residential_address());
		basic_informationImpl.setCurrent_residential_address_phone(getCurrent_residential_address_phone());
		basic_informationImpl.setEmergency_contact(getEmergency_contact());
		basic_informationImpl.setEmergency_contact_relation(getEmergency_contact_relation());
		basic_informationImpl.setEmergency_contact_phone(getEmergency_contact_phone());
		basic_informationImpl.setCompanyId(getCompanyId());
		basic_informationImpl.setCreateuser(getCreateuser());
		basic_informationImpl.setCreateDate(getCreateDate());
		basic_informationImpl.setModifieduser(getModifieduser());
		basic_informationImpl.setModifiedDate(getModifiedDate());

		basic_informationImpl.resetOriginalValues();

		return basic_informationImpl;
	}

	@Override
	public int compareTo(basic_information basic_information) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				basic_information.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof basic_information)) {
			return false;
		}

		basic_information basic_information = (basic_information)obj;

		long primaryKey = basic_information.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		basic_informationModelImpl basic_informationModelImpl = this;

		basic_informationModelImpl._originalUuid = basic_informationModelImpl._uuid;

		basic_informationModelImpl._originalCompanyId = basic_informationModelImpl._companyId;

		basic_informationModelImpl._setOriginalCompanyId = false;

		basic_informationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<basic_information> toCacheModel() {
		basic_informationCacheModel basic_informationCacheModel = new basic_informationCacheModel();

		basic_informationCacheModel.uuid = getUuid();

		String uuid = basic_informationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			basic_informationCacheModel.uuid = null;
		}

		basic_informationCacheModel.staffId = getStaffId();

		basic_informationCacheModel.userId = getUserId();

		basic_informationCacheModel.name = getName();

		String name = basic_informationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			basic_informationCacheModel.name = null;
		}

		basic_informationCacheModel.sex = getSex();

		String sex = basic_informationCacheModel.sex;

		if ((sex != null) && (sex.length() == 0)) {
			basic_informationCacheModel.sex = null;
		}

		basic_informationCacheModel.id_number = getId_number();

		String id_number = basic_informationCacheModel.id_number;

		if ((id_number != null) && (id_number.length() == 0)) {
			basic_informationCacheModel.id_number = null;
		}

		basic_informationCacheModel.nation = getNation();

		String nation = basic_informationCacheModel.nation;

		if ((nation != null) && (nation.length() == 0)) {
			basic_informationCacheModel.nation = null;
		}

		basic_informationCacheModel.place_of_origin = getPlace_of_origin();

		String place_of_origin = basic_informationCacheModel.place_of_origin;

		if ((place_of_origin != null) && (place_of_origin.length() == 0)) {
			basic_informationCacheModel.place_of_origin = null;
		}

		basic_informationCacheModel.account_properties = getAccount_properties();

		String account_properties = basic_informationCacheModel.account_properties;

		if ((account_properties != null) && (account_properties.length() == 0)) {
			basic_informationCacheModel.account_properties = null;
		}

		Date birth = getBirth();

		if (birth != null) {
			basic_informationCacheModel.birth = birth.getTime();
		}
		else {
			basic_informationCacheModel.birth = Long.MIN_VALUE;
		}

		basic_informationCacheModel.marital_status = getMarital_status();

		String marital_status = basic_informationCacheModel.marital_status;

		if ((marital_status != null) && (marital_status.length() == 0)) {
			basic_informationCacheModel.marital_status = null;
		}

		basic_informationCacheModel.highest_degree = getHighest_degree();

		String highest_degree = basic_informationCacheModel.highest_degree;

		if ((highest_degree != null) && (highest_degree.length() == 0)) {
			basic_informationCacheModel.highest_degree = null;
		}

		basic_informationCacheModel.political_background = getPolitical_background();

		String political_background = basic_informationCacheModel.political_background;

		if ((political_background != null) &&
				(political_background.length() == 0)) {
			basic_informationCacheModel.political_background = null;
		}

		basic_informationCacheModel.file_location = getFile_location();

		String file_location = basic_informationCacheModel.file_location;

		if ((file_location != null) && (file_location.length() == 0)) {
			basic_informationCacheModel.file_location = null;
		}

		basic_informationCacheModel.base_pay = getBase_pay();

		basic_informationCacheModel.performance_pay = getPerformance_pay();

		basic_informationCacheModel.health = getHealth();

		String health = basic_informationCacheModel.health;

		if ((health != null) && (health.length() == 0)) {
			basic_informationCacheModel.health = null;
		}

		basic_informationCacheModel.contact_phone = getContact_phone();

		String contact_phone = basic_informationCacheModel.contact_phone;

		if ((contact_phone != null) && (contact_phone.length() == 0)) {
			basic_informationCacheModel.contact_phone = null;
		}

		basic_informationCacheModel.mail = getMail();

		String mail = basic_informationCacheModel.mail;

		if ((mail != null) && (mail.length() == 0)) {
			basic_informationCacheModel.mail = null;
		}

		basic_informationCacheModel.domicile = getDomicile();

		String domicile = basic_informationCacheModel.domicile;

		if ((domicile != null) && (domicile.length() == 0)) {
			basic_informationCacheModel.domicile = null;
		}

		basic_informationCacheModel.residence_phone = getResidence_phone();

		String residence_phone = basic_informationCacheModel.residence_phone;

		if ((residence_phone != null) && (residence_phone.length() == 0)) {
			basic_informationCacheModel.residence_phone = null;
		}

		basic_informationCacheModel.current_residential_address = getCurrent_residential_address();

		String current_residential_address = basic_informationCacheModel.current_residential_address;

		if ((current_residential_address != null) &&
				(current_residential_address.length() == 0)) {
			basic_informationCacheModel.current_residential_address = null;
		}

		basic_informationCacheModel.current_residential_address_phone = getCurrent_residential_address_phone();

		String current_residential_address_phone = basic_informationCacheModel.current_residential_address_phone;

		if ((current_residential_address_phone != null) &&
				(current_residential_address_phone.length() == 0)) {
			basic_informationCacheModel.current_residential_address_phone = null;
		}

		basic_informationCacheModel.emergency_contact = getEmergency_contact();

		String emergency_contact = basic_informationCacheModel.emergency_contact;

		if ((emergency_contact != null) && (emergency_contact.length() == 0)) {
			basic_informationCacheModel.emergency_contact = null;
		}

		basic_informationCacheModel.emergency_contact_relation = getEmergency_contact_relation();

		String emergency_contact_relation = basic_informationCacheModel.emergency_contact_relation;

		if ((emergency_contact_relation != null) &&
				(emergency_contact_relation.length() == 0)) {
			basic_informationCacheModel.emergency_contact_relation = null;
		}

		basic_informationCacheModel.emergency_contact_phone = getEmergency_contact_phone();

		String emergency_contact_phone = basic_informationCacheModel.emergency_contact_phone;

		if ((emergency_contact_phone != null) &&
				(emergency_contact_phone.length() == 0)) {
			basic_informationCacheModel.emergency_contact_phone = null;
		}

		basic_informationCacheModel.companyId = getCompanyId();

		basic_informationCacheModel.createuser = getCreateuser();

		Date createDate = getCreateDate();

		if (createDate != null) {
			basic_informationCacheModel.createDate = createDate.getTime();
		}
		else {
			basic_informationCacheModel.createDate = Long.MIN_VALUE;
		}

		basic_informationCacheModel.modifieduser = getModifieduser();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			basic_informationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			basic_informationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return basic_informationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(63);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", staffId=");
		sb.append(getStaffId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", sex=");
		sb.append(getSex());
		sb.append(", id_number=");
		sb.append(getId_number());
		sb.append(", nation=");
		sb.append(getNation());
		sb.append(", place_of_origin=");
		sb.append(getPlace_of_origin());
		sb.append(", account_properties=");
		sb.append(getAccount_properties());
		sb.append(", birth=");
		sb.append(getBirth());
		sb.append(", marital_status=");
		sb.append(getMarital_status());
		sb.append(", highest_degree=");
		sb.append(getHighest_degree());
		sb.append(", political_background=");
		sb.append(getPolitical_background());
		sb.append(", file_location=");
		sb.append(getFile_location());
		sb.append(", base_pay=");
		sb.append(getBase_pay());
		sb.append(", performance_pay=");
		sb.append(getPerformance_pay());
		sb.append(", health=");
		sb.append(getHealth());
		sb.append(", contact_phone=");
		sb.append(getContact_phone());
		sb.append(", mail=");
		sb.append(getMail());
		sb.append(", domicile=");
		sb.append(getDomicile());
		sb.append(", residence_phone=");
		sb.append(getResidence_phone());
		sb.append(", current_residential_address=");
		sb.append(getCurrent_residential_address());
		sb.append(", current_residential_address_phone=");
		sb.append(getCurrent_residential_address_phone());
		sb.append(", emergency_contact=");
		sb.append(getEmergency_contact());
		sb.append(", emergency_contact_relation=");
		sb.append(getEmergency_contact_relation());
		sb.append(", emergency_contact_phone=");
		sb.append(getEmergency_contact_phone());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createuser=");
		sb.append(getCreateuser());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifieduser=");
		sb.append(getModifieduser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(97);

		sb.append("<model><model-name>");
		sb.append("com.shuntian.portlet.intranet.model.basic_information");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>staffId</column-name><column-value><![CDATA[");
		sb.append(getStaffId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sex</column-name><column-value><![CDATA[");
		sb.append(getSex());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_number</column-name><column-value><![CDATA[");
		sb.append(getId_number());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nation</column-name><column-value><![CDATA[");
		sb.append(getNation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>place_of_origin</column-name><column-value><![CDATA[");
		sb.append(getPlace_of_origin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>account_properties</column-name><column-value><![CDATA[");
		sb.append(getAccount_properties());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birth</column-name><column-value><![CDATA[");
		sb.append(getBirth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marital_status</column-name><column-value><![CDATA[");
		sb.append(getMarital_status());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>highest_degree</column-name><column-value><![CDATA[");
		sb.append(getHighest_degree());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>political_background</column-name><column-value><![CDATA[");
		sb.append(getPolitical_background());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>file_location</column-name><column-value><![CDATA[");
		sb.append(getFile_location());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>base_pay</column-name><column-value><![CDATA[");
		sb.append(getBase_pay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>performance_pay</column-name><column-value><![CDATA[");
		sb.append(getPerformance_pay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>health</column-name><column-value><![CDATA[");
		sb.append(getHealth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contact_phone</column-name><column-value><![CDATA[");
		sb.append(getContact_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mail</column-name><column-value><![CDATA[");
		sb.append(getMail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>domicile</column-name><column-value><![CDATA[");
		sb.append(getDomicile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>residence_phone</column-name><column-value><![CDATA[");
		sb.append(getResidence_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>current_residential_address</column-name><column-value><![CDATA[");
		sb.append(getCurrent_residential_address());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>current_residential_address_phone</column-name><column-value><![CDATA[");
		sb.append(getCurrent_residential_address_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emergency_contact</column-name><column-value><![CDATA[");
		sb.append(getEmergency_contact());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emergency_contact_relation</column-name><column-value><![CDATA[");
		sb.append(getEmergency_contact_relation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emergency_contact_phone</column-name><column-value><![CDATA[");
		sb.append(getEmergency_contact_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createuser</column-name><column-value><![CDATA[");
		sb.append(getCreateuser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifieduser</column-name><column-value><![CDATA[");
		sb.append(getModifieduser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = basic_information.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			basic_information.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _staffId;
	private long _userId;
	private String _userUuid;
	private String _name;
	private String _sex;
	private String _id_number;
	private String _nation;
	private String _place_of_origin;
	private String _account_properties;
	private Date _birth;
	private String _marital_status;
	private String _highest_degree;
	private String _political_background;
	private String _file_location;
	private double _base_pay;
	private double _performance_pay;
	private String _health;
	private String _contact_phone;
	private String _mail;
	private String _domicile;
	private String _residence_phone;
	private String _current_residential_address;
	private String _current_residential_address_phone;
	private String _emergency_contact;
	private String _emergency_contact_relation;
	private String _emergency_contact_phone;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _createuser;
	private Date _createDate;
	private long _modifieduser;
	private Date _modifiedDate;
	private long _columnBitmask;
	private basic_information _escapedModel;
}