/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.shuntian.portlet.intranet.model.basic_information;
import com.shuntian.portlet.intranet.service.basic_informationLocalServiceUtil;

/**
 * The extended model base implementation for the basic_information service. Represents a row in the &quot;Intranet_basic_information&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link basic_informationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see basic_informationImpl
 * @see com.shuntian.portlet.intranet.model.basic_information
 * @generated
 */
public abstract class basic_informationBaseImpl
	extends basic_informationModelImpl implements basic_information {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a basic_information model instance should use the {@link basic_information} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			basic_informationLocalServiceUtil.addbasic_information(this);
		}
		else {
			basic_informationLocalServiceUtil.updatebasic_information(this);
		}
	}
}