/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.ContainerModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;
import com.liferay.portlet.trash.model.TrashEntry;
import com.liferay.portlet.trash.service.TrashEntryLocalServiceUtil;

import com.shuntian.portlet.intranet.model.ext_information;
import com.shuntian.portlet.intranet.model.ext_informationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ext_information service. Represents a row in the &quot;Intranet_ext_information&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.shuntian.portlet.intranet.model.ext_informationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ext_informationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ext_informationImpl
 * @see com.shuntian.portlet.intranet.model.ext_information
 * @see com.shuntian.portlet.intranet.model.ext_informationModel
 * @generated
 */
public class ext_informationModelImpl extends BaseModelImpl<ext_information>
	implements ext_informationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ext_information model instance should use the {@link com.shuntian.portlet.intranet.model.ext_information} interface instead.
	 */
	public static final String TABLE_NAME = "Intranet_ext_information";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "extId", Types.BIGINT },
			{ "staffId", Types.BIGINT },
			{ "open_city", Types.VARCHAR },
			{ "bank_name", Types.VARCHAR },
			{ "bankid", Types.VARCHAR },
			{ "labor_contract_start", Types.TIMESTAMP },
			{ "labor_contract_end", Types.TIMESTAMP },
			{ "probation_period_start", Types.TIMESTAMP },
			{ "probation_period_end", Types.TIMESTAMP },
			{ "indured_location", Types.VARCHAR },
			{ "frist_insured", Types.TIMESTAMP },
			{ "is_insured", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "createuser", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifieduser", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Intranet_ext_information (uuid_ VARCHAR(75) null,extId LONG not null primary key,staffId LONG,open_city VARCHAR(75) null,bank_name VARCHAR(75) null,bankid VARCHAR(75) null,labor_contract_start DATE null,labor_contract_end DATE null,probation_period_start DATE null,probation_period_end DATE null,indured_location VARCHAR(75) null,frist_insured DATE null,is_insured VARCHAR(75) null,companyId LONG,createuser LONG,createDate DATE null,modifieduser LONG,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Intranet_ext_information";
	public static final String ORDER_BY_JPQL = " ORDER BY ext_information.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Intranet_ext_information.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.shuntian.portlet.intranet.model.ext_information"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.shuntian.portlet.intranet.model.ext_information"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.shuntian.portlet.intranet.model.ext_information"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long UUID_COLUMN_BITMASK = 2L;
	public static long CREATEDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.shuntian.portlet.intranet.model.ext_information"));

	public ext_informationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _extId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExtId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _extId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ext_information.class;
	}

	@Override
	public String getModelClassName() {
		return ext_information.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("extId", getExtId());
		attributes.put("staffId", getStaffId());
		attributes.put("open_city", getOpen_city());
		attributes.put("bank_name", getBank_name());
		attributes.put("bankid", getBankid());
		attributes.put("labor_contract_start", getLabor_contract_start());
		attributes.put("labor_contract_end", getLabor_contract_end());
		attributes.put("probation_period_start", getProbation_period_start());
		attributes.put("probation_period_end", getProbation_period_end());
		attributes.put("indured_location", getIndured_location());
		attributes.put("frist_insured", getFrist_insured());
		attributes.put("is_insured", getIs_insured());
		attributes.put("companyId", getCompanyId());
		attributes.put("createuser", getCreateuser());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifieduser", getModifieduser());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long extId = (Long)attributes.get("extId");

		if (extId != null) {
			setExtId(extId);
		}

		Long staffId = (Long)attributes.get("staffId");

		if (staffId != null) {
			setStaffId(staffId);
		}

		String open_city = (String)attributes.get("open_city");

		if (open_city != null) {
			setOpen_city(open_city);
		}

		String bank_name = (String)attributes.get("bank_name");

		if (bank_name != null) {
			setBank_name(bank_name);
		}

		String bankid = (String)attributes.get("bankid");

		if (bankid != null) {
			setBankid(bankid);
		}

		Date labor_contract_start = (Date)attributes.get("labor_contract_start");

		if (labor_contract_start != null) {
			setLabor_contract_start(labor_contract_start);
		}

		Date labor_contract_end = (Date)attributes.get("labor_contract_end");

		if (labor_contract_end != null) {
			setLabor_contract_end(labor_contract_end);
		}

		Date probation_period_start = (Date)attributes.get(
				"probation_period_start");

		if (probation_period_start != null) {
			setProbation_period_start(probation_period_start);
		}

		Date probation_period_end = (Date)attributes.get("probation_period_end");

		if (probation_period_end != null) {
			setProbation_period_end(probation_period_end);
		}

		String indured_location = (String)attributes.get("indured_location");

		if (indured_location != null) {
			setIndured_location(indured_location);
		}

		Date frist_insured = (Date)attributes.get("frist_insured");

		if (frist_insured != null) {
			setFrist_insured(frist_insured);
		}

		String is_insured = (String)attributes.get("is_insured");

		if (is_insured != null) {
			setIs_insured(is_insured);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long createuser = (Long)attributes.get("createuser");

		if (createuser != null) {
			setCreateuser(createuser);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long modifieduser = (Long)attributes.get("modifieduser");

		if (modifieduser != null) {
			setModifieduser(modifieduser);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getExtId() {
		return _extId;
	}

	@Override
	public void setExtId(long extId) {
		_extId = extId;
	}

	@Override
	public long getStaffId() {
		return _staffId;
	}

	@Override
	public void setStaffId(long staffId) {
		_staffId = staffId;
	}

	@Override
	public String getOpen_city() {
		if (_open_city == null) {
			return StringPool.BLANK;
		}
		else {
			return _open_city;
		}
	}

	@Override
	public void setOpen_city(String open_city) {
		_open_city = open_city;
	}

	@Override
	public String getBank_name() {
		if (_bank_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _bank_name;
		}
	}

	@Override
	public void setBank_name(String bank_name) {
		_bank_name = bank_name;
	}

	@Override
	public String getBankid() {
		if (_bankid == null) {
			return StringPool.BLANK;
		}
		else {
			return _bankid;
		}
	}

	@Override
	public void setBankid(String bankid) {
		_bankid = bankid;
	}

	@Override
	public Date getLabor_contract_start() {
		return _labor_contract_start;
	}

	@Override
	public void setLabor_contract_start(Date labor_contract_start) {
		_labor_contract_start = labor_contract_start;
	}

	@Override
	public Date getLabor_contract_end() {
		return _labor_contract_end;
	}

	@Override
	public void setLabor_contract_end(Date labor_contract_end) {
		_labor_contract_end = labor_contract_end;
	}

	@Override
	public Date getProbation_period_start() {
		return _probation_period_start;
	}

	@Override
	public void setProbation_period_start(Date probation_period_start) {
		_probation_period_start = probation_period_start;
	}

	@Override
	public Date getProbation_period_end() {
		return _probation_period_end;
	}

	@Override
	public void setProbation_period_end(Date probation_period_end) {
		_probation_period_end = probation_period_end;
	}

	@Override
	public String getIndured_location() {
		if (_indured_location == null) {
			return StringPool.BLANK;
		}
		else {
			return _indured_location;
		}
	}

	@Override
	public void setIndured_location(String indured_location) {
		_indured_location = indured_location;
	}

	@Override
	public Date getFrist_insured() {
		return _frist_insured;
	}

	@Override
	public void setFrist_insured(Date frist_insured) {
		_frist_insured = frist_insured;
	}

	@Override
	public String getIs_insured() {
		if (_is_insured == null) {
			return StringPool.BLANK;
		}
		else {
			return _is_insured;
		}
	}

	@Override
	public void setIs_insured(String is_insured) {
		_is_insured = is_insured;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getCreateuser() {
		return _createuser;
	}

	@Override
	public void setCreateuser(long createuser) {
		_createuser = createuser;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getModifieduser() {
		return _modifieduser;
	}

	@Override
	public void setModifieduser(long modifieduser) {
		_modifieduser = modifieduser;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ext_information.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException {
		if (!isInTrash()) {
			return null;
		}

		TrashEntry trashEntry = TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		TrashHandler trashHandler = getTrashHandler();

		if (!Validator.isNull(trashHandler.getContainerModelClassName())) {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler = TrashHandlerRegistryUtil.getTrashHandler(trashHandler.getContainerModelClassName());

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public TrashHandler getTrashHandler() {
		return TrashHandlerRegistryUtil.getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		TrashHandler trashHandler = getTrashHandler();

		if ((trashHandler == null) ||
				Validator.isNull(trashHandler.getContainerModelClassName())) {
			return false;
		}

		try {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception e) {
		}

		return false;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ext_information.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ext_information toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ext_information)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ext_informationImpl ext_informationImpl = new ext_informationImpl();

		ext_informationImpl.setUuid(getUuid());
		ext_informationImpl.setExtId(getExtId());
		ext_informationImpl.setStaffId(getStaffId());
		ext_informationImpl.setOpen_city(getOpen_city());
		ext_informationImpl.setBank_name(getBank_name());
		ext_informationImpl.setBankid(getBankid());
		ext_informationImpl.setLabor_contract_start(getLabor_contract_start());
		ext_informationImpl.setLabor_contract_end(getLabor_contract_end());
		ext_informationImpl.setProbation_period_start(getProbation_period_start());
		ext_informationImpl.setProbation_period_end(getProbation_period_end());
		ext_informationImpl.setIndured_location(getIndured_location());
		ext_informationImpl.setFrist_insured(getFrist_insured());
		ext_informationImpl.setIs_insured(getIs_insured());
		ext_informationImpl.setCompanyId(getCompanyId());
		ext_informationImpl.setCreateuser(getCreateuser());
		ext_informationImpl.setCreateDate(getCreateDate());
		ext_informationImpl.setModifieduser(getModifieduser());
		ext_informationImpl.setModifiedDate(getModifiedDate());

		ext_informationImpl.resetOriginalValues();

		return ext_informationImpl;
	}

	@Override
	public int compareTo(ext_information ext_information) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				ext_information.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ext_information)) {
			return false;
		}

		ext_information ext_information = (ext_information)obj;

		long primaryKey = ext_information.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ext_informationModelImpl ext_informationModelImpl = this;

		ext_informationModelImpl._originalUuid = ext_informationModelImpl._uuid;

		ext_informationModelImpl._originalCompanyId = ext_informationModelImpl._companyId;

		ext_informationModelImpl._setOriginalCompanyId = false;

		ext_informationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ext_information> toCacheModel() {
		ext_informationCacheModel ext_informationCacheModel = new ext_informationCacheModel();

		ext_informationCacheModel.uuid = getUuid();

		String uuid = ext_informationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ext_informationCacheModel.uuid = null;
		}

		ext_informationCacheModel.extId = getExtId();

		ext_informationCacheModel.staffId = getStaffId();

		ext_informationCacheModel.open_city = getOpen_city();

		String open_city = ext_informationCacheModel.open_city;

		if ((open_city != null) && (open_city.length() == 0)) {
			ext_informationCacheModel.open_city = null;
		}

		ext_informationCacheModel.bank_name = getBank_name();

		String bank_name = ext_informationCacheModel.bank_name;

		if ((bank_name != null) && (bank_name.length() == 0)) {
			ext_informationCacheModel.bank_name = null;
		}

		ext_informationCacheModel.bankid = getBankid();

		String bankid = ext_informationCacheModel.bankid;

		if ((bankid != null) && (bankid.length() == 0)) {
			ext_informationCacheModel.bankid = null;
		}

		Date labor_contract_start = getLabor_contract_start();

		if (labor_contract_start != null) {
			ext_informationCacheModel.labor_contract_start = labor_contract_start.getTime();
		}
		else {
			ext_informationCacheModel.labor_contract_start = Long.MIN_VALUE;
		}

		Date labor_contract_end = getLabor_contract_end();

		if (labor_contract_end != null) {
			ext_informationCacheModel.labor_contract_end = labor_contract_end.getTime();
		}
		else {
			ext_informationCacheModel.labor_contract_end = Long.MIN_VALUE;
		}

		Date probation_period_start = getProbation_period_start();

		if (probation_period_start != null) {
			ext_informationCacheModel.probation_period_start = probation_period_start.getTime();
		}
		else {
			ext_informationCacheModel.probation_period_start = Long.MIN_VALUE;
		}

		Date probation_period_end = getProbation_period_end();

		if (probation_period_end != null) {
			ext_informationCacheModel.probation_period_end = probation_period_end.getTime();
		}
		else {
			ext_informationCacheModel.probation_period_end = Long.MIN_VALUE;
		}

		ext_informationCacheModel.indured_location = getIndured_location();

		String indured_location = ext_informationCacheModel.indured_location;

		if ((indured_location != null) && (indured_location.length() == 0)) {
			ext_informationCacheModel.indured_location = null;
		}

		Date frist_insured = getFrist_insured();

		if (frist_insured != null) {
			ext_informationCacheModel.frist_insured = frist_insured.getTime();
		}
		else {
			ext_informationCacheModel.frist_insured = Long.MIN_VALUE;
		}

		ext_informationCacheModel.is_insured = getIs_insured();

		String is_insured = ext_informationCacheModel.is_insured;

		if ((is_insured != null) && (is_insured.length() == 0)) {
			ext_informationCacheModel.is_insured = null;
		}

		ext_informationCacheModel.companyId = getCompanyId();

		ext_informationCacheModel.createuser = getCreateuser();

		Date createDate = getCreateDate();

		if (createDate != null) {
			ext_informationCacheModel.createDate = createDate.getTime();
		}
		else {
			ext_informationCacheModel.createDate = Long.MIN_VALUE;
		}

		ext_informationCacheModel.modifieduser = getModifieduser();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ext_informationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ext_informationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return ext_informationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", extId=");
		sb.append(getExtId());
		sb.append(", staffId=");
		sb.append(getStaffId());
		sb.append(", open_city=");
		sb.append(getOpen_city());
		sb.append(", bank_name=");
		sb.append(getBank_name());
		sb.append(", bankid=");
		sb.append(getBankid());
		sb.append(", labor_contract_start=");
		sb.append(getLabor_contract_start());
		sb.append(", labor_contract_end=");
		sb.append(getLabor_contract_end());
		sb.append(", probation_period_start=");
		sb.append(getProbation_period_start());
		sb.append(", probation_period_end=");
		sb.append(getProbation_period_end());
		sb.append(", indured_location=");
		sb.append(getIndured_location());
		sb.append(", frist_insured=");
		sb.append(getFrist_insured());
		sb.append(", is_insured=");
		sb.append(getIs_insured());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createuser=");
		sb.append(getCreateuser());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifieduser=");
		sb.append(getModifieduser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("com.shuntian.portlet.intranet.model.ext_information");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extId</column-name><column-value><![CDATA[");
		sb.append(getExtId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>staffId</column-name><column-value><![CDATA[");
		sb.append(getStaffId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>open_city</column-name><column-value><![CDATA[");
		sb.append(getOpen_city());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bank_name</column-name><column-value><![CDATA[");
		sb.append(getBank_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bankid</column-name><column-value><![CDATA[");
		sb.append(getBankid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>labor_contract_start</column-name><column-value><![CDATA[");
		sb.append(getLabor_contract_start());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>labor_contract_end</column-name><column-value><![CDATA[");
		sb.append(getLabor_contract_end());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>probation_period_start</column-name><column-value><![CDATA[");
		sb.append(getProbation_period_start());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>probation_period_end</column-name><column-value><![CDATA[");
		sb.append(getProbation_period_end());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>indured_location</column-name><column-value><![CDATA[");
		sb.append(getIndured_location());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>frist_insured</column-name><column-value><![CDATA[");
		sb.append(getFrist_insured());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>is_insured</column-name><column-value><![CDATA[");
		sb.append(getIs_insured());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createuser</column-name><column-value><![CDATA[");
		sb.append(getCreateuser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifieduser</column-name><column-value><![CDATA[");
		sb.append(getModifieduser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ext_information.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ext_information.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _extId;
	private long _staffId;
	private String _open_city;
	private String _bank_name;
	private String _bankid;
	private Date _labor_contract_start;
	private Date _labor_contract_end;
	private Date _probation_period_start;
	private Date _probation_period_end;
	private String _indured_location;
	private Date _frist_insured;
	private String _is_insured;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _createuser;
	private Date _createDate;
	private long _modifieduser;
	private Date _modifiedDate;
	private long _columnBitmask;
	private ext_information _escapedModel;
}