/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.ContainerModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;
import com.liferay.portlet.trash.model.TrashEntry;
import com.liferay.portlet.trash.service.TrashEntryLocalServiceUtil;

import com.shuntian.portlet.intranet.model.work;
import com.shuntian.portlet.intranet.model.workModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the work service. Represents a row in the &quot;Intranet_work&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.shuntian.portlet.intranet.model.workModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link workImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see workImpl
 * @see com.shuntian.portlet.intranet.model.work
 * @see com.shuntian.portlet.intranet.model.workModel
 * @generated
 */
public class workModelImpl extends BaseModelImpl<work> implements workModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a work model instance should use the {@link com.shuntian.portlet.intranet.model.work} interface instead.
	 */
	public static final String TABLE_NAME = "Intranet_work";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "workId", Types.BIGINT },
			{ "satffId", Types.BIGINT },
			{ "witness", Types.VARCHAR },
			{ "once_job", Types.VARCHAR },
			{ "work_unit", Types.VARCHAR },
			{ "contact_phone", Types.VARCHAR },
			{ "start_stop_time", Types.TIMESTAMP },
			{ "companyId", Types.BIGINT },
			{ "createuser", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifieduser", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Intranet_work (uuid_ VARCHAR(75) null,workId LONG not null primary key,satffId LONG,witness VARCHAR(75) null,once_job VARCHAR(75) null,work_unit VARCHAR(75) null,contact_phone VARCHAR(75) null,start_stop_time DATE null,companyId LONG,createuser LONG,createDate DATE null,modifieduser LONG,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Intranet_work";
	public static final String ORDER_BY_JPQL = " ORDER BY work.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Intranet_work.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.shuntian.portlet.intranet.model.work"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.shuntian.portlet.intranet.model.work"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.shuntian.portlet.intranet.model.work"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long UUID_COLUMN_BITMASK = 2L;
	public static long CREATEDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.shuntian.portlet.intranet.model.work"));

	public workModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return work.class;
	}

	@Override
	public String getModelClassName() {
		return work.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("workId", getWorkId());
		attributes.put("satffId", getSatffId());
		attributes.put("witness", getWitness());
		attributes.put("once_job", getOnce_job());
		attributes.put("work_unit", getWork_unit());
		attributes.put("contact_phone", getContact_phone());
		attributes.put("start_stop_time", getStart_stop_time());
		attributes.put("companyId", getCompanyId());
		attributes.put("createuser", getCreateuser());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifieduser", getModifieduser());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long workId = (Long)attributes.get("workId");

		if (workId != null) {
			setWorkId(workId);
		}

		Long satffId = (Long)attributes.get("satffId");

		if (satffId != null) {
			setSatffId(satffId);
		}

		String witness = (String)attributes.get("witness");

		if (witness != null) {
			setWitness(witness);
		}

		String once_job = (String)attributes.get("once_job");

		if (once_job != null) {
			setOnce_job(once_job);
		}

		String work_unit = (String)attributes.get("work_unit");

		if (work_unit != null) {
			setWork_unit(work_unit);
		}

		String contact_phone = (String)attributes.get("contact_phone");

		if (contact_phone != null) {
			setContact_phone(contact_phone);
		}

		Date start_stop_time = (Date)attributes.get("start_stop_time");

		if (start_stop_time != null) {
			setStart_stop_time(start_stop_time);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long createuser = (Long)attributes.get("createuser");

		if (createuser != null) {
			setCreateuser(createuser);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long modifieduser = (Long)attributes.get("modifieduser");

		if (modifieduser != null) {
			setModifieduser(modifieduser);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getWorkId() {
		return _workId;
	}

	@Override
	public void setWorkId(long workId) {
		_workId = workId;
	}

	@Override
	public long getSatffId() {
		return _satffId;
	}

	@Override
	public void setSatffId(long satffId) {
		_satffId = satffId;
	}

	@Override
	public String getWitness() {
		if (_witness == null) {
			return StringPool.BLANK;
		}
		else {
			return _witness;
		}
	}

	@Override
	public void setWitness(String witness) {
		_witness = witness;
	}

	@Override
	public String getOnce_job() {
		if (_once_job == null) {
			return StringPool.BLANK;
		}
		else {
			return _once_job;
		}
	}

	@Override
	public void setOnce_job(String once_job) {
		_once_job = once_job;
	}

	@Override
	public String getWork_unit() {
		if (_work_unit == null) {
			return StringPool.BLANK;
		}
		else {
			return _work_unit;
		}
	}

	@Override
	public void setWork_unit(String work_unit) {
		_work_unit = work_unit;
	}

	@Override
	public String getContact_phone() {
		if (_contact_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _contact_phone;
		}
	}

	@Override
	public void setContact_phone(String contact_phone) {
		_contact_phone = contact_phone;
	}

	@Override
	public Date getStart_stop_time() {
		return _start_stop_time;
	}

	@Override
	public void setStart_stop_time(Date start_stop_time) {
		_start_stop_time = start_stop_time;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getCreateuser() {
		return _createuser;
	}

	@Override
	public void setCreateuser(long createuser) {
		_createuser = createuser;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getModifieduser() {
		return _modifieduser;
	}

	@Override
	public void setModifieduser(long modifieduser) {
		_modifieduser = modifieduser;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				work.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException {
		if (!isInTrash()) {
			return null;
		}

		TrashEntry trashEntry = TrashEntryLocalServiceUtil.fetchEntry(getModelClassName(),
				getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		TrashHandler trashHandler = getTrashHandler();

		if (!Validator.isNull(trashHandler.getContainerModelClassName())) {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler = TrashHandlerRegistryUtil.getTrashHandler(trashHandler.getContainerModelClassName());

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public TrashHandler getTrashHandler() {
		return TrashHandlerRegistryUtil.getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		TrashHandler trashHandler = getTrashHandler();

		if ((trashHandler == null) ||
				Validator.isNull(trashHandler.getContainerModelClassName())) {
			return false;
		}

		try {
			ContainerModel containerModel = trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception e) {
		}

		return false;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			work.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public work toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (work)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		workImpl workImpl = new workImpl();

		workImpl.setUuid(getUuid());
		workImpl.setWorkId(getWorkId());
		workImpl.setSatffId(getSatffId());
		workImpl.setWitness(getWitness());
		workImpl.setOnce_job(getOnce_job());
		workImpl.setWork_unit(getWork_unit());
		workImpl.setContact_phone(getContact_phone());
		workImpl.setStart_stop_time(getStart_stop_time());
		workImpl.setCompanyId(getCompanyId());
		workImpl.setCreateuser(getCreateuser());
		workImpl.setCreateDate(getCreateDate());
		workImpl.setModifieduser(getModifieduser());
		workImpl.setModifiedDate(getModifiedDate());

		workImpl.resetOriginalValues();

		return workImpl;
	}

	@Override
	public int compareTo(work work) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), work.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof work)) {
			return false;
		}

		work work = (work)obj;

		long primaryKey = work.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		workModelImpl workModelImpl = this;

		workModelImpl._originalUuid = workModelImpl._uuid;

		workModelImpl._originalCompanyId = workModelImpl._companyId;

		workModelImpl._setOriginalCompanyId = false;

		workModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<work> toCacheModel() {
		workCacheModel workCacheModel = new workCacheModel();

		workCacheModel.uuid = getUuid();

		String uuid = workCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			workCacheModel.uuid = null;
		}

		workCacheModel.workId = getWorkId();

		workCacheModel.satffId = getSatffId();

		workCacheModel.witness = getWitness();

		String witness = workCacheModel.witness;

		if ((witness != null) && (witness.length() == 0)) {
			workCacheModel.witness = null;
		}

		workCacheModel.once_job = getOnce_job();

		String once_job = workCacheModel.once_job;

		if ((once_job != null) && (once_job.length() == 0)) {
			workCacheModel.once_job = null;
		}

		workCacheModel.work_unit = getWork_unit();

		String work_unit = workCacheModel.work_unit;

		if ((work_unit != null) && (work_unit.length() == 0)) {
			workCacheModel.work_unit = null;
		}

		workCacheModel.contact_phone = getContact_phone();

		String contact_phone = workCacheModel.contact_phone;

		if ((contact_phone != null) && (contact_phone.length() == 0)) {
			workCacheModel.contact_phone = null;
		}

		Date start_stop_time = getStart_stop_time();

		if (start_stop_time != null) {
			workCacheModel.start_stop_time = start_stop_time.getTime();
		}
		else {
			workCacheModel.start_stop_time = Long.MIN_VALUE;
		}

		workCacheModel.companyId = getCompanyId();

		workCacheModel.createuser = getCreateuser();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workCacheModel.createDate = createDate.getTime();
		}
		else {
			workCacheModel.createDate = Long.MIN_VALUE;
		}

		workCacheModel.modifieduser = getModifieduser();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return workCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", workId=");
		sb.append(getWorkId());
		sb.append(", satffId=");
		sb.append(getSatffId());
		sb.append(", witness=");
		sb.append(getWitness());
		sb.append(", once_job=");
		sb.append(getOnce_job());
		sb.append(", work_unit=");
		sb.append(getWork_unit());
		sb.append(", contact_phone=");
		sb.append(getContact_phone());
		sb.append(", start_stop_time=");
		sb.append(getStart_stop_time());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createuser=");
		sb.append(getCreateuser());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifieduser=");
		sb.append(getModifieduser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.shuntian.portlet.intranet.model.work");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workId</column-name><column-value><![CDATA[");
		sb.append(getWorkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>satffId</column-name><column-value><![CDATA[");
		sb.append(getSatffId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>witness</column-name><column-value><![CDATA[");
		sb.append(getWitness());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>once_job</column-name><column-value><![CDATA[");
		sb.append(getOnce_job());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>work_unit</column-name><column-value><![CDATA[");
		sb.append(getWork_unit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contact_phone</column-name><column-value><![CDATA[");
		sb.append(getContact_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>start_stop_time</column-name><column-value><![CDATA[");
		sb.append(getStart_stop_time());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createuser</column-name><column-value><![CDATA[");
		sb.append(getCreateuser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifieduser</column-name><column-value><![CDATA[");
		sb.append(getModifieduser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = work.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { work.class };
	private String _uuid;
	private String _originalUuid;
	private long _workId;
	private long _satffId;
	private String _witness;
	private String _once_job;
	private String _work_unit;
	private String _contact_phone;
	private Date _start_stop_time;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _createuser;
	private Date _createDate;
	private long _modifieduser;
	private Date _modifiedDate;
	private long _columnBitmask;
	private work _escapedModel;
}